<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
        <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Domain\DB.Client.Domain\DB.Client.Domain.csproj" />
        <ProjectReference Include="..\..\DB.Client.Backend.Host.Core\DB.Client.Backend.Host.Core.csproj" />
        <ProjectReference Include="..\..\..\Domain\DB.Client.Domain.Infrastructure\DB.Client.Domain.Infrastructure.csproj" />
    </ItemGroup>

</Project>
