<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.26.1" />
        <PackageReference Include="Grpc" Version="2.46.6" />
        <PackageReference Include="Grpc.Tools" Version="2.63.0" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\..\..\Protos\product.proto" Link="Protos\product.proto" GrpcServices="Server" />
        <Protobuf Include="..\..\..\Protos\product_service.proto" Link="Protos\product_service.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\DB.Client.Backend.Host.Core\DB.Client.Backend.Host.Core.csproj" />
        <ProjectReference Include="..\..\..\Domain\DB.Client.Domain.Infrastructure\DB.Client.Domain.Infrastructure.csproj" />
        <ProjectReference Include="..\..\..\Domain\DB.Client.Domain\DB.Client.Domain.csproj" />
        <ProjectReference Include="..\DB.Client.Backend.DBInteraction.Redis\DB.Client.Backend.DBInteraction.Redis.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
            <HintPath>..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.7\Microsoft.AspNetCore.Routing.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\..\Domain\DB.Client.Domain.Converters\ConverterExtensions.cs" />
    </ItemGroup>

</Project>
