<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>DB.Client.Backend.Host</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DryIoc.dll" Version="5.4.3" />
        <PackageReference Include="DryIoc.Microsoft.DependencyInjection" Version="6.2.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
        <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DB.Client.Backend.Host.Core\DB.Client.Backend.Host.Core.csproj" />
        <ProjectReference Include="..\Modules\DB.Client.Backend.DBInteraction.MongoDB\DB.Client.Backend.DBInteraction.MongoDB.csproj" />
        <ProjectReference Include="..\Modules\DB.Client.Backend.Grpc\DB.Client.Backend.Grpc.csproj" />
        <ProjectReference Include="..\Modules\DB.Client.Backend.Entrypoint.Grpc\DB.Client.Backend.Entrypoint.Grpc.csproj" />
        <ProjectReference Include="..\Modules\DB.Client.Backend.DBInteraction.PostgreSQL\DB.Client.Backend.DBInteraction.PostgreSQL.csproj" />
        <ProjectReference Include="..\Modules\DB.Client.Backend.DBInteraction.Redis\DB.Client.Backend.DBInteraction.Redis.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
